name: Publish docs via GitHub Pages

on: push
  # push:
  #   branches:
  #     - master
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v2

      - name: Add dependencies
        run: >-
          poetry add mkdocs pymdown-extensions python-markdown-math

      - name: Deploy docs
        run: >-
          poetry run mkdocs gh-deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # CUSTOM_DOMAIN: optionaldomain.com
